### PR TITLE
Include checkUpdate.js in install

### PR DESCRIPTION
**Pull request by mlazari**

### CODE REVIEW

**Comment by yleflour** [comment]
I am not sure what this does exactly. Could you please link this to an issue?

**Comment by mlazari** [comment]
Sorry, I forgot to add a description. This is my first pull request on github :)
I've installed this tool with `npm install -g yo generator-rn-toolbox`, then I tried to generate icons with `yo rn-toolbox:assets --icon ../ic_launcher.png`, but i give me this error:
`events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module '../../checkUpdate'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-rn-toolbox/generators/checkversion/index.js:3:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)`
I think checkUpdate.js is missing in `/usr/local/lib/node_modules/generator-rn-toolbox/` because it is not included in files array in package.json. However I'm not sure, because I'm not familiar with npm packages.

**Comment by Almouro** [comment]
Hi @mlazari! :)
Yes I can confirm I have the same issue.

Thanks for your PR and congrats on your first PR on Github 🎉 !

**Comment by Almouro** [comment]
@mlazari just merged and published your fix, it's working for me! Thanks again ;)

**Comment by mlazari** [comment]
@Almouro Thank you, too :)

**Pull request merged**
